name: "Weather Station"
uuid: "station-1"
altitude: 452.1
std_sea_level_pressure: 1013.25
api:
    host: "http://localhost"
    port: 8000
    user: "admin"
sensor_config:
    i2c_address: 0x76
    type: "bme280"
